web:
  last_stable_version: 'master'
  protected_access: false
  eshop_url: 'https://obchod.altar.cz/'
  menu_position_fixed: true
  show_home_button_on_homepage: false
  show_home_button_on_routes: true
  name: 'DrD+ pravidla a odkazy'
  title_smiley: 'ðŸ“š'
  show_debug_contacts: false
google:
  analytics_id: 'UA-121206931-1'